// Gate-Level Netlist - smart_soc_top
// Generated by: Cadence Genus 21.14
// Date: 2026-06-10 01:44:02
// Library: slow_125c

module smart_soc_top (
    input  wire        CLK_CORE,
    input  wire        CLK_MEM,
    input  wire        CLK_PER,
    input  wire        CLK_REF,
    input  wire        RST_N,
    input  wire [63:0] DATA_IN,
    output wire [63:0] DATA_OUT,
    inout  wire [31:0] GPIO
);

  // Internal wires
  wire clk_core_buf, clk_mem_buf, clk_per_buf;
  wire [63:0] core_data_out;
  wire [31:0] mem_addr;
  wire        mem_we, mem_re;
  wire [63:0] mem_data_in, mem_data_out;

  // Clock buffers
  BUFX4 u_clkbuf_core (.A(CLK_CORE), .Y(clk_core_buf));
  BUFX4 u_clkbuf_mem  (.A(CLK_MEM),  .Y(clk_mem_buf));
  BUFX2 u_clkbuf_per  (.A(CLK_PER),  .Y(clk_per_buf));

  // Core instantiation
  core_top u_core (
    .CLK      (clk_core_buf),
    .RST_N    (RST_N),
    .DATA_IN  (DATA_IN),
    .DATA_OUT (core_data_out),
    .MEM_ADDR (mem_addr),
    .MEM_WE   (mem_we),
    .MEM_RE   (mem_re),
    .MEM_DIN  (mem_data_in),
    .MEM_DOUT (mem_data_out)
  );

  // Memory subsystem
  mem_subsystem u_mem (
    .CLK      (clk_mem_buf),
    .RST_N    (RST_N),
    .ADDR     (mem_addr),
    .WE       (mem_we),
    .RE       (mem_re),
    .DATA_IN  (mem_data_in),
    .DATA_OUT (mem_data_out)
  );

  // IO subsystem
  io_subsystem u_io (
    .CLK      (clk_per_buf),
    .RST_N    (RST_N),
    .GPIO     (GPIO)
  );

  // Debug subsystem
  debug_top u_debug (
    .CLK      (clk_per_buf),
    .RST_N    (RST_N)
  );

  // Output assignment
  BUFX2 u_outbuf [63:0] (.A(core_data_out), .Y(DATA_OUT));

endmodule

// ALU submodule (partial)
module alu_64 (
    input  wire        CLK, RST_N,
    input  wire [63:0] A, B,
    input  wire [3:0]  OP,
    output wire [63:0] RESULT,
    output wire        CARRY, OVERFLOW, ZERO
);
  wire [63:0] add_result, and_result, or_result, xor_result;
  wire [63:0] mux_out1, mux_out2;

  // Adder chain (critical path)
  NAND2X1 u_add_g0  (.A(A[0]),  .B(B[0]),  .Y(add_result[0]));
  XOR2X1  u_add_p0  (.A(A[0]),  .B(B[0]),  .Y(add_result[1]));
  AND2X1  u_and0    (.A(A[0]),  .B(B[0]),  .Y(and_result[0]));
  OR2X1   u_or0     (.A(A[0]),  .B(B[0]),  .Y(or_result[0]));
  XOR2X1  u_xor0    (.A(A[0]),  .B(B[0]),  .Y(xor_result[0]));

  // Result register (endpoint of critical path)
  DFFX1 reg_result [63:0] (.D(mux_out2), .CK(CLK), .Q(RESULT));
  DFFX1 reg_carry       (.D(add_result[63]), .CK(CLK), .Q(CARRY));

endmodule
